# fly.toml app configuration file generated for translate-discordbot on 2026-02-22T07:14:39+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'translate-discordbot'
primary_region = 'nrt'

[build]
  dockerfile = 'Dockerfile'

# Discord Bot は常時稼働させる必要があるため、1台を維持するように設定します。
# ※実際に1台にするには、初回デプロイ後に `fly scale count 1` の実行が必要です。
[deploy]
  min_machines_running = 1

# [[services]] ブロックは不要なため削除しました。

[[vm]]
  memory = '1gb'
  cpus = 1
  memory_mb = 1024
